use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :weebservices, WeebServicesWeb.Endpoint,
  url: [host: "weeb.services", port: String.to_integer(System.get_env("PORT") || "1539")],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE") || raise "environment variable SECRET_KEY_BASE is missing."

# Do not print debug messages in production
config :logger, level: :info
